version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-north-1"
    ECR_REPO_NAME: "django-backend"
    STACK_NAME: "sam-prod-stack"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing AWS SAM CLI..."
      - pip install --upgrade aws-sam-cli

  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo "Deploying SAM stack..."
      - sam deploy --stack-name $STACK_NAME --image-repository $REPOSITORY_URI --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset

artifacts:
  files:
    - '**/*'
